---
- name: include secret vars
  include_vars: secret.yml

- name: add authorized_key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: mount /tmp as fstmp
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,size=32m,noatime,mode=1777
    state: present

- name: mount /var/tmp as fstmp
  mount:
    path: /var/tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,size=32m,noatime,mode=1777
    state: present

- name: swapoff
  script: swapoff.sh
  register: result
  changed_when: result.rc == 254
  failed_when: result.rc not in [0, 254]

- name: disable swap service
  systemd:
    name: dphys-swapfile
    enabled: no

- name: copy rsyslog.conf
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: create /root/bin
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy ip-notify.sh
  template:
    src: ip-notify.sh.j2
    dest: /root/bin/ip-notify.sh
    owner: root
    group: root
    mode: 0755

- name: copy ip-notify.service
  copy:
    src: ip-notify.service
    dest: /etc/systemd/system/ip-notify.service
    owner: root
    group: root
    mode: 0644

- name: enable systemd-networkd.service
  systemd:
    name: systemd-networkd.service
    enabled: yes

- name: enable systemd-networkd-wait-online.service
  systemd:
    name: systemd-networkd-wait-online.service
    enabled: yes

- name: enable ip-notify.service
  systemd:
    name: ip-notify.service
    enabled: yes

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
